<?php if (isset($errors)) : ?>
    <div class="alert alert-danger mt-3 alert-dismissible fade show" role="alert">
        <?php foreach ($errors as $error): ?>
            <?php echo $error ?>
        <?php endforeach; ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endif; ?>

<form method="post" enctype="multipart/form-data" class="my-3">
    <input type="hidden" name="old_photo" value="<?php echo $client['image']; ?>">
    <div class="form-group">
        <label for="loginEdit">Логин</label>
        <input type="text" class="form-control" id="loginEdit" name="login" value="<?php echo $client['login'] ?>">
    </div>
    <div class="form-group">
        <label for="passwordEdit">Пароль</label>
        <input type="password" class="form-control" name="password" id="passwordEdit"
               value="<?php echo $client['password'] ?>">
    </div>
    <div class="form-group">
        <label for="emailEdit">Email</label>
        <input type="email" class="form-control" id="emailEdit" name="email" value="<?php echo $client['email'] ?>">
    </div>
    <div class="form-group">
        <label for="nameEdit">Имя пользователя</label>
        <input type="text" class="form-control" id="nameEdit" name="name" value="<?php echo $client['name'] ?>">
    </div>
    <div class="form-group">
        <label for="surnameEdit">Фамилия пользователя</label>
        <input type="text" class="form-control" id="surnameEdit" name="surname"
               value="<?php echo $client['surname'] ?>">
    </div>
    <div class="form-group">
        <label for="phoneEdit">Телефон</label>
        <input type="text" class="form-control" id="phoneEdit" name="phone" value="<?php echo $client['phone'] ?>">
    </div>
    <div class="form-group">
        <label>Фотография</label>
        <div id="previewImage">
            <img src="<?php if ($client['image'] === '') {
                echo 'https://via.placeholder.com/900x675.png'; } else {
                echo '/repository/photos/', $client['image'];
            } ?>" alt="">
        </div>
        <label>Миниатюра</label>
        <div id="previewImage">
            <img src="<?php if ($client['image'] === '') {
                echo 'https://via.placeholder.com/100x100.png'; } else {
                echo '/repository/thumbs/', $client['image'];
            } ?>" alt="">
        </div>
        <input type="file" class="form-control-file mt-3" name="photo" id="photoRegister"
               onchange="document.getElementById('previewImage').remove();"
               accept="image/jpeg, image/png,image/gif">

    </div>
    <div class="form-group">
        <label for="addressEdit">Адрес</label>
        <input type="text" class="form-control" id="addressEdit" name="address"
               value="<?php echo $client['address'] ?>">
    </div>
    <button type="submit" class="btn btn-success">Сохранить изменения</button>
</form>