<?php if (isset($errors)) : ?>
    <div class="alert alert-danger mt-3 alert-dismissible fade show" role="alert">
        <?php foreach ($errors as $error): ?>
            <?php echo $error ?>
        <?php endforeach; ?>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<?php endif; ?>

<form method="post" enctype="multipart/form-data" class="my-3">
    <div class="form-group">
        <label for="loginEdit">Логин</label>
        <input type="text" class="form-control" id="loginEdit" name="login" >
    </div>
    <div class="form-group">
        <label for="passwordEdit">Пароль</label>
        <input type="password" class="form-control" name="password" id="passwordEdit"
               >
    </div>
    <div class="form-group">
        <label for="emailEdit">Email</label>
        <input type="email" class="form-control" id="emailEdit" name="email" >
    </div>
    <div class="form-group">
        <label for="nameEdit">Имя пользователя</label>
        <input type="text" class="form-control" id="nameEdit" name="name" >
    </div>
    <div class="form-group">
        <label for="surnameEdit">Фамилия пользователя</label>
        <input type="text" class="form-control" id="surnameEdit" name="surname"
               >
    </div>
    <div class="form-group">
        <label for="phoneEdit">Телефон</label>
        <input type="text" class="form-control" id="phoneEdit" name="phone" >
    </div>
    <div class="form-group">
        <label>Фотография</label>
        <input type="file" class="form-control-file mt-3" name="photo" id="photoRegister" onchange="document.getElementById('previewImage').remove();"
               accept="image/jpeg, image/png,image/gif">
    </div>
    <div class="form-group">
        <label for="addressEdit">Адрес</label>
        <input type="text" class="form-control" id="addressEdit" name="address">
    </div>
    <div class="form-group">
        <label for="activeEditEdit">Активирован</label>
        <div class="form-check ">
            <input class="form-check-input" type="radio"
                   name="active"  id="inlineRadio1" value="1">
            <label class="form-check-label" for="inlineRadio1">Да</label>
        </div>
        <div class="form-check ">
            <input class="form-check-input" type="radio" checked
                   name="active" id="inlineRadio2" value="0">
            <label class="form-check-label"  for="inlineRadio2">Нет</label>
        </div>
    </div>
    <div class="form-group">
        <label for="clubEdit">Членство в клубе</label>
        <select name="club_type" class="custom-select" id="clubEdit">
            <?php foreach ($club_state as $key => $state): ?>
                <option <?php if($key === 0) echo 'selected'?> value="<?php echo $key ?>"><?php echo $state ?></option>
            <?php endforeach; ?>
            <?php ?>
        </select>
    </div>
    <button type="submit" class="btn btn-success">Сохранить изменения</button>
</form>


<script>
    IMask(document.getElementById('phoneEdit'), {
        mask: '+{7}(000)000-00-00'
    });
</script>