<form method="post">

    <div class="form-group">
        <label for="loginDash">Логин</label>
        <input type="text" class="form-control" name="login" id="loginDash" >
    </div>
    <div class="form-group">
        <label for="passDash">Пароль</label>
        <input type="password" class="form-control" name="password" id="passDash" >
    </div>
    <button type="submit" class="btn btn-primary">Войти</button>

</form>